<a href="https://colab.research.google.com/github/koriatul/pytn-ks-011/blob/main/Komputasi_Matematika_dengan_pustaka_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**WORKSHOP NUMPY**

In [ ]:
import numpy as np
np.__version__

'1.22.4'

**PYTHON LIST**

In [ ]:
gpas_as_list = [4.0,3.2,3.5]
gpas_as_list.append(4.0)
gpas_as_list

[4.0, 3.2, 3.5, 4.0]

In [ ]:
gpas_as_list.insert(1, "belum ada")
gpas_as_list

[4.0, 'belum ada', 3.2, 3.5, 4.0]

In [ ]:
gpas_as_list.pop(1)
gpas_as_list

[4.0, 3.2, 3.5, 4.0]

**NumPy Array**

In [ ]:
gpas = np.array(gpas_as_list)
gpas.dtype

dtype('float64')

In [ ]:
gpas.size

4

**Study Log**

In [ ]:
study_minutes = np.zeros(100)
study_minutes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
%whos

Variable        Type       Data/Info
------------------------------------
gpas            ndarray    4: 4 elems, type `float64`, 32 bytes
gpas_as_list    list       n=4
np              module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
study_minutes   ndarray    100: 100 elems, type `float64`, 800 bytes


**ARRAY MULTIDIMENSI**

In [ ]:
students_gpas = np.array([
    [4.0,3.3,3.5,4.0],
    [3.96,3.94,4.0,4.0],
    [3.2,3.8,4.0,4.0]
], np.float16)
students_gpas

array([[4.  , 3.3 , 3.5 , 4.  ],
       [3.96, 3.94, 4.  , 4.  ],
       [3.2 , 3.8 , 4.  , 4.  ]], dtype=float16)

In [ ]:
students_gpas.ndim

2

In [ ]:
students_gpas.shape

(3, 4)

In [ ]:
students_gpas[2]

array([3.2, 3.8, 4. , 4. ], dtype=float16)

In [ ]:
students_gpas[2][3]

4.0

**Studi Log Multidimensi**

In [ ]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])
study_minutes.shape

(2, 100)

In [ ]:
study_minutes [1][0] = 60
study_minutes

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [60.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [ ]:
rand = np.random. RandomState(57)
fake_log = rand.randint(30, 180, size =100 , dtype =np.uint16)
fake_log

array([122,  35,  30, 135, 109,  89, 150, 138, 128, 173,  70, 130, 149,
       167, 169,  42, 159, 111,  88,  45, 159, 164, 128, 127,  59, 159,
        35,  95,  98,  35, 126, 119,  39, 111,  80, 172,  97, 172, 134,
        56,  90, 167, 115, 176, 146,  94, 128, 143,  85,  42,  84,  43,
       106, 149, 125, 142, 160, 120,  32,  36, 155,  67,  60, 156, 163,
        47, 138, 129,  46,  68, 110, 149,  34, 104,  89,  53, 134, 150,
        82,  76,  84,  43, 168, 163,  59,  77, 122, 150, 136,  52,  85,
       116, 106,  51,  36,  35,  39, 140,  34, 141], dtype=uint16)

In [ ]:
[fake_log[1] , fake_log[21]]

[35, 164]

In [ ]:
fake_log[[1,21]]

array([ 35, 164], dtype=uint16)

In [ ]:
index = np.array([
    [1, 21],
    [1, 2]
])
fake_log[index]

array([[ 35, 164],
       [ 35,  30]], dtype=uint16)

In [ ]:
study_minutes = np.append(study_minutes , [fake_log])
study_minutes

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,  60.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

In [ ]:
study_minutes[study_minutes < 60]
study_minutes[(study_minutes < 60 ) & (study_minutes > 9)]

array([35., 30., 42., 45., 59., 35., 35., 39., 56., 42., 43., 32., 36.,
       47., 46., 34., 53., 43., 59., 52., 51., 36., 35., 39., 34.])

**Slicing Array**

In [ ]:
practice = np.arange(42)
practice.shape = (7,6)
practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [ ]:
practice[2,1]

13

In [ ]:
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

**Copy vs View**

In [ ]:
practice_list = [1,2,3]
practice_list_copy=practice_list[:]
practice_list, practice_list_copy
practice_list_copy[0]= 12345
practice_list, practice_list_copy

([1, 2, 3], [12345, 2, 3])

In [ ]:
not_copied = practice[:]
not_copied [0, 0] = 12345
practice , not_copied

(array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [ ]:
print(not_copied.base)

[[12345     1     2     3     4     5]
 [    6     7     8     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]
 [   24    25    26    27    28    29]
 [   30    31    32    33    34    35]
 [   36    37    38    39    40    41]]


In [ ]:
not_copied.base is practice

True

**Filter Array dengan Kondisi**

In [ ]:
#mencari durasi belajar dibawah 1 jam
fake_log < 60
fake_log[fake_log <60]

array([35, 30, 42, 45, 59, 35, 35, 39, 56, 42, 43, 32, 36, 47, 46, 34, 53,
       43, 59, 52, 51, 36, 35, 39, 34], dtype=uint16)

In [ ]:
results = []
for value in fake_log:
  if value < 60:
    results.append(value)
    
np.array(results)

array([35, 30, 42, 45, 59, 35, 35, 39, 56, 42, 43, 32, 36, 47, 46, 34, 53,
       43, 59, 52, 51, 36, 35, 39, 34], dtype=uint16)

In [ ]:
study_minutes = np.zeros(100, np.uint16)
study_miniutes = np.append(study_minutes ,[fake_log])
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [ ]:
study_minutes[study_minutes < 60]
study_minutes[(study_minutes< 60) & study_minutes > 0]

array([], dtype=uint16)

**Aljabar Linear**

In [ ]:
orders = np.array([
    [2, 0, 0, 0],
    [1, 0, 2, 4],
    [1, 2, 1, 0],
    [4, 6, 0, 2]
])
totals = np.array([20000, 32000 , 20000, 61000])
prices = np.linalg.solve(orders , totals)
prices

array([10000.,  2500.,  5000.,  3000.])

In [ ]:
orders @ prices

array([20000., 32000., 20000., 61000.])

**Fungsi Universal**

In [ ]:
a, b = np.split(np.arange(1,11), 2)
a, b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [ ]:
a + b

array([ 7,  9, 11, 13, 15])

In [ ]:
a * b

array([ 6, 14, 24, 36, 50])

In [ ]:
a - b

array([-5, -5, -5, -5, -5])

In [ ]:
b - a

array([5, 5, 5, 5, 5])

In [ ]:
a + 3

array([4, 5, 6, 7, 8])

In [ ]:
a + np.repeat(3, 5)

array([4, 5, 6, 7, 8])

In [ ]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
x1, x2

(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]), array([0., 1., 2.]))

In [ ]:
np.add(x1, x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [ ]:
np.add( x1 , 2)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

**Operasi Matriks Lainya**

In [ ]:
study_less = study_minutes[(study_minutes < 60) & study_minutes > 0]
print(study_less)
np.add.reduce(study_less)

[]


0

In [ ]:
np.sum(study_minutes)

0

**Matplotlib**

In [ ]:
import matplotlib.pyplot as plt


In [ ]:
study_minutes[study_minutes > 0]

array([], dtype=uint16)

In [ ]:
plt.his(study_minutes[study_minutes > 0])
plt.plot()

AttributeError: ignored