<a href="https://colab.research.google.com/github/koriatul/pytn-ks-011/blob/main/Menguasai_python_tingkat_pemula.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DATA STUCTURES**

LIST

In [ ]:
#LIST
my_list =[1 ,2 ,3]
print(my_list)

[1, 2, 3]


In [ ]:
my_list + [4, 5]

[1, 2, 3, 4, 5]

In [ ]:
print(my_list * 2)

[1, 2, 3, 1, 2, 3]


In [ ]:
#menmabahkan 1 data
my_list.append(4)
print(my_list)

[1, 2, 3, 4]


In [ ]:
my_list.append([4,5])
print(my_list)

[1, 2, 3, 4, [4, 5]]


In [ ]:
#menambah banyak data
mylist = [1 , 2, 3]
print(mylist)
mylist.extend([4, 5, 6])
print(mylist)

[1, 2, 3]
[1, 2, 3, 4, 5, 6]


In [ ]:
#menghapus item
mylist.remove(4)
print(mylist)

[1, 2, 3, 5, 6]


In [ ]:
#menghapus list dala list
print(my_list)
my_list.remove([4,5])
print(my_list)

[1, 2, 3, 4, [4, 5]]
[1, 2, 3, 4]


Dictionaries

In [ ]:
student =dict(name='Billy', age= 38)
print(student['name'])

Billy


In [ ]:
print(student['age'])

38


In [ ]:
#menghapus data
print(student)
del student['age']
print(student)

{'name': 'Billy', 'age': 38}
{'name': 'Billy'}


In [ ]:
student ={'name':'Raka', 'age': 17}
print(student.keys())

dict_keys(['name', 'age'])


In [ ]:
print(student.values())

dict_values(['Raka', 17])


Tuple

In [ ]:
people = ('Raka',('Kode','random'))
print(people)

('Raka', ('Kode', 'random'))


In [ ]:
#mengakses informasi
print(people[0])
print(people[1])
print(people[1][0])

Raka
('Kode', 'random')
Kode


In [ ]:
#tuple slicing
numbers = (1 , 2 , 3 , 4)
new_numbers = numbers[0], numbers[1:3]
print(new_numbers)
print(numbers)

(1, (2, 3))
(1, 2, 3, 4)


In [ ]:
#konversi
email_attr = ('to','from','cc','bcc','subject','body')
email_attr_list = list(email_attr)
email_attr_list.sort()
print(email_attr_list)

TypeError: ignored

Files

In [ ]:
#membuka file
myfile = open('teks.txt', 'w')
myfile.write('halo text file!\n')

16

In [ ]:
myfile.write('selamat tinggal text file!\n')

27

In [ ]:
myfile.close()

In [ ]:
#membaca file baris perbaris
myfile = open('teks.txt')
myfile.readline()

''

In [ ]:
myfile.readline()

'halo text file!\n'

In [ ]:
open('teks.txt').read()

''

In [ ]:
print(open('teks.txt').read())

In [ ]:
x , y , z = 43 , 44 , 45
message ='spam'
data = {'a': 1 , 'b': 2}
list = [1 , 2 , 3 , 4 ]
file = open('teks.txt' , 'w')
file.write(message + '\n')


5

In [ ]:
file.write('%s, %s, %s\n' % (x, y ,z))

11

In [ ]:
#konversi data
file.write(str(list) + '$' + str(data) + '\n')

30

In [ ]:
file.close()

**Loop & Iterators**

while loop

In [ ]:
message = "spam"
while message != '':
  print(message, end=' ')
  message = message[1:]

spam pam am m 

In [ ]:
a = 0
b = 13
while a < b:
  print(a, end=' ')
  a = a + 1

0 1 2 3 4 5 6 7 8 9 10 11 12 

In [ ]:
while True:
  name = input('Enter name:')
  if name == 'stop' : break
  age = input('Enter age:')
  print('Hello', name, '=>', int(age) **2 )


Enter name:raka
Enter age:17
Hello raka => 289
Enter name:stop


For Loop

In [ ]:
for word in ['raka','billy', 'kode']:
  print(word , end='\n')

raka
billy
kode


In [ ]:
sum = 0
for i in [1,2,3,4]:
  sum = sum + i

In [ ]:
sum

10

In [ ]:
prod = 1
for item in [1,2,3,4]: prod *=item

In [ ]:
prod

24

In [ ]:
text = 'foxyfox'
words = ('is', 'great', 'animal')
for chara in text: print(chara, end=' ')

f o x y f o x 

In [ ]:
for word in words : print(word , end='...')

is...great...animal...

In [ ]:
coor = [(1,2) , (3,4) , (5,6)]
for (x,y) in coor: print(x,y)

1 2
3 4
5 6


In [ ]:
x = 0
while (x < 100):
  x+=2
  print(x)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


**Branching in python**

if statement

In [ ]:
if 1:
  print('True')

True


In [ ]:
if not 1:
  print('True')
else:
    print('False')

False


In [ ]:
#percabangan ganda
age = input('enter your age: ')
if int (age) * 365 > 2000:
  print('time to retire!')
elif int (age) * 365 > 10000:
    print('lots of time left!')
else:
      print('time to get started!')

enter your age: 26
time to retire!


In [ ]:
user_age = input('enter your age : ')
age = int(user_age) * 365 
if age >= 9490:
  print('you are a jedi master now . go learn from master yoda!! ')
elif age>= 8395 and age < 9490:
    print('becoming jedi knight')
else:
      print('you are a young padawan')

enter your age : 33
you are a jedi master now . go learn from master yoda!! 


**Function & Package**

function

In [ ]:
def add(a , b):
  return a + b

In [ ]:
add(5,4)

9

In [ ]:
add_things = add (10,4)
print(add_things)

14


In [ ]:
def add_and_print(a , b):
  print(a + b)

In [ ]:
add_and_print(1,3)

4


In [ ]:
x = add_and_print(5,3)

8


In [ ]:
print(x)

None


In [ ]:
def intersection(first_word , second_word):
  result = []
  for x in first_word:
    if x in second_word:
      result.append(x)
      return result

In [ ]:
word1 = 'spam'
word2 = 'scam'
char_of_intersect = intersection(word1 , word2)
print(char_of_intersect)

['s']


built in function

In [ ]:
#menampilkan nilai absolut
print(abs(-123))

123


In [ ]:
numbers = 222
print(isinstance(numbers, int))

True


In [ ]:
numbers = 222
print(isinstance(numbers, dict))

False


In [ ]:
numbers = [1,2,3,4,5,6]
print(max(numbers))
print(min(numbers))

6
1


In [ ]:
alphas = ['a' , 'b' , 'z']
print(max(alphas))
print(min(alphas))

z
a


In [ ]:
languages = ['py','js','go','c']
print(languages.index('go'))

2


In [ ]:
languages.sort()
print(languages)

['c', 'go', 'js', 'py']


In [ ]:
name ='raka'
print(name)
name.replace('k','c')
name.capitalize()

raka


'Raka'

In [ ]:
import math
print(math.factorial(3))

6


In [ ]:
import requests

In [ ]:
r = requests.get('https://api.github.com/event')
print(r)

<Response [404]>


In [ ]:
def outerfun (a ,b):
  def innerFun (c, d):
    return c + d
  return innerFun(a, b)
  res = outer
  Fun (5,10) 
  print(res)

**Bonus Chapter**

Pengenalan NumPy

In [ ]:
import numpy as np

In [ ]:
height = [1.75,1.68,1.8,1.81,1.69]
weight = [66.4,49.22,66.3,88.56,65.4]
np_height = np.array(height)
np_weight = np.array(weight)
bmi = np_weight/np_height ** 2
print(bmi)

[21.68163265 17.43905896 20.46296296 27.03214188 22.8983579 ]


In [ ]:
mixed_array = np.array([1.0, 'is', True])
print(mixed_array)

['1.0' 'is' 'True']


In [ ]:
numlist =[1,2,3]
nparray = np.array([1,2,3])
numlist + numlist

[1, 2, 3, 1, 2, 3]

In [ ]:
bmi

array([21.68163265, 17.43905896, 20.46296296, 27.03214188, 22.8983579 ])

In [ ]:
bmi > 24

array([False, False, False,  True, False])

In [ ]:
bmi[bmi > 24]

array([27.03214188])

statistik dasar dengan NumPy

In [ ]:
height = np.round(np.random.normal(1.75,0.2,5000), 2)
height

array([1.85, 1.52, 1.57, ..., 1.19, 1.75, 1.95])

In [ ]:
len(height)


5000

In [ ]:
weight = np.round(np.random.normal(60.32,15,5000), 2)
weight

array([93.01, 72.65, 51.89, ..., 55.65, 47.82, 57.99])

In [ ]:
len(weight)

5000

In [ ]:
np_city = np.column_stack((height, weight))
#mencari nilai rata-rata
np.mean(np_city[:,0])

1.745586

In [ ]:
#mencari nilai tengah
np.median(np_city[:,0])

1.75

In [ ]:
#mencari standar deviasi
np.std(np_city[:,0])

0.20226303815576388

NumPy Array 2D

In [ ]:
height = [1.75,1.68,1.8,1.81,1.69]
weight = [66.4,49.22,66.3,88.56,65.4]
type(height)

list

In [ ]:
np_2d = np.array([[1.75,1.68,1.8,1.81,1.69],
                  [66.4,49.22,66.3,88.56,65.4]])
np_2d

array([[ 1.75,  1.68,  1.8 ,  1.81,  1.69],
       [66.4 , 49.22, 66.3 , 88.56, 65.4 ]])

In [ ]:
np_2d.shape

(2, 5)

In [ ]:
np_2d[0]

array([1.75, 1.68, 1.8 , 1.81, 1.69])

In [ ]:
np_2d[0][2]

1.8

In [ ]:
np_2d[:,1:3]

array([[ 1.68,  1.8 ],
       [49.22, 66.3 ]])

In [ ]:
np_2d[1,:]

array([66.4 , 49.22, 66.3 , 88.56, 65.4 ])

quiz

In [ ]:
names = np.array([['idaz', 'anggara'],
                  ['dear','kurniawan']])
names 

array([['idaz', 'anggara'],
       ['dear', 'kurniawan']], dtype='<U9')

In [ ]:
print(names[0])

['idaz' 'anggara']


In [ ]:
x = sub()