<a href="https://colab.research.google.com/github/koriatul/pytn-ks-011/blob/main/Sesi_4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Quiz

In [47]:
def calc(a,b,c):
    if (a.isnumeric()==True) and (c.isnumeric()==True):
        a = int(a)
        c = int(c)
        if b == 'x':
            print('hasil dari', a,b,c, 'adalah', a*c)
        elif b == '+':
            print('hasil dari', a,b,c, 'adalah', a+c)
        elif b == ':':
            print('hasil dari', a,b,c, 'adalah', a/c)
        elif b == '-':
            print('hasil dari', a,b,c, 'adalah', a-c)
        elif b == '^':
            print('hasil dari', a,b,c, 'adalah', a**c)
        else:
            print('operator', b, 'tidak ditemukan')
    else:
        print('salah')
        
a=(input('masukan angka1 ='))
b=(input('masukan operator ='))
c=(input('masukan angka2 ='))

calc(a,b,c)

masukan angka1 =5
masukan operator =5
masukan angka2 =5
operator 5 tidak ditemukan


In [48]:
a = '3'
c.isnumeric()

True

In [49]:
try:
    int('string')
except:
    print('bukan string')

bukan string


**Numpy**

In [50]:
import numpy as np

In [51]:
a = np.array ([1,2,3])
a

array([1, 2, 3])

<h2> One dimensional array <h2>

Indexing dan Slicing

In [52]:
a[1]

2

In [53]:
array1 =[1,2,3,4,5,6,7,8]
array1[3:]

[4, 5, 6, 7, 8]

In [54]:
array1[3:]

[4, 5, 6, 7, 8]

In [55]:
np.shape

<function numpy.shape(a)>

2 dimensional array consist of list of lists

In [56]:
list_of_lists = [[1,2,3,],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
list_of_lists = [[1,2,3,],[4,5,6],[7,8,9]]
array_2 = np.array(list_of_lists)
array_2
print(array_2.shape)

(3, 3)


In [58]:
list_of_lists_2 =[[1,2],[3,4],[5,6]]
array_3 = np.array(list_of_lists_2)
print(array_3.shape)
array_3

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

<h3> Creating array <h3>

In [59]:
# np.zeros
print(np.zeros(8)) #1D
print(np.zeros([3,2])) #2D

[0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [80]:
# np.ones untuk membuat array dengan isi angka 1
print(np.ones(4))
print(np.ones([4,2]))

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [84]:
# np.empty untuk membuat array dengan isi random dan bergantung status memori
np.empty(5)
np.empty((3,2))

array([[2.34526164e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [83]:
# np.arange untuk membuat array dengan jarak antar elemen
print(np.arange(10))
print(np.arange(0,10,2)) #(start,stop,step)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [85]:
np.arange(0,4,2) #start,stop,step. list np mulai dari angka 0 hingga 4 dengan kenaikan 2x untuk setiap loncatan

array([0, 2])

In [64]:
c = np.array([1,2,3,4,3,2,1,5,6,7,8,9])

#append
print(np.append(c,[10,11]))
#delete
print(np.delete(c,2))
#sort
print(np.sort(c))

[ 1  2  3  4  3  2  1  5  6  7  8  9 10 11]
[1 2 4 3 2 1 5 6 7 8 9]
[1 1 2 2 3 3 4 5 6 7 8 9]


In [65]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [66]:
c = np.array([1,2,3,4,3,2,1,5,6,7,8,9,10])
d = np.zeros((2,2))
#ndim
print(c.ndim)
print(d.ndim)

#size
print(c.size)
print(d.size)

#reshape
print(c[:-1].reshape(3,4))

1
2
13
4
[[1 2 3 4]
 [3 2 1 5]
 [6 7 8 9]]


In [67]:
array_3 = np.array([[1,2,3,4]])
array_4 = np.array([[5,6,7,8]])
np.vstack([array_3,array_4])
print(np.hstack([array_3,array_4]))

[[1 2 3 4 5 6 7 8]]


In [68]:
array_5 = np.array([1,2,3,4])
array_6 = np.array([5,6,7,8])
np.hstack([array_5,array_6])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
np.append(array_3,[5,6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
#np.newaxis
array_4 = np.array([4,5,6])
array_4[np.newaxis]
print(array_4[:,np.newaxis].shape)

(3, 1)


In [71]:
#np.expand_dims
array_7 = np.array([3,4,5,6,7,8,9])
array_8 = np.expand_dims(array_7,axis=1)
array_9 = np.expand_dims(array_7,axis=0)
print(array_8)
print(array_8.shape)
print(array_9)
print(array_9.shape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(7, 1)
[[3 4 5 6 7 8 9]]
(1, 7)


<h3> Operasi Matematika pada array sifatnya broadcast <h3>

In [72]:
array_7 = np.array([3,4,5,6,7,8,9])
array_7*2

array([ 6,  8, 10, 12, 14, 16, 18])

In [73]:
array_10 = np.array([[1,2,3],[4,5,6]])
array_10-4

array([[-3, -2, -1],
       [ 0,  1,  2]])

<h3> Filtering Array <h3>

In [74]:
array_7 = np.array([3,4,5,6,7,8,9])
print(array_7[array_7>5])
print(array_7[array_7==8])
print(array_7[array_7<=4])

[6 7 8 9]
[8]
[3 4]


In [75]:
array_11 = np.array([[3,5,7],[8,9,10],[-1,-2,-3]])
array_11.shape
print(array_11[array_11>5])

[ 7  8  9 10]


Quiz 

In [86]:
# quiz

n=int(input('how tall ? '))
t=0

if n%2==0:
   t=n-1
else:
   t=n

for i in range(0,t):
   if (t-2*i)>0: 
      print(' '*i+'*'*(t-2*i))
   else:
      k=t-i-1
      print(' '*k+'*'*(t-2*k))

how tall ? 8
*******
 *****
  ***
   *
  ***
 *****
*******


<h3> hstack, vstack, hsplit, vsplit<h3> 

In [88]:
#stack
array_14 = np.array([3,4,5,6,7])
array_15 = np.array([7,8,9,10,11])
print('Stack secara Vertikal')
print(np.vstack([array_14,array_15]))
print('Stack secara Horizontal')
print(np.hstack([array_14,array_15]))

Stack secara Vertikal
[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
Stack secara Horizontal
[ 3  4  5  6  7  7  8  9 10 11]


In [89]:
#hsplit
array_16 = np.array([3,4,5,6,7,8])
array_split = np.hsplit(array_16,2)
(array_split)

[array([3, 4, 5]), array([6, 7, 8])]

In [90]:
#vsplit
array_19 = np.array([[1,2,3,4],[4,5,6,7]])
print(array_19.shape)
print('Horizontal Split')
print(np.hsplit(array_19,2))
print('Vertical Split')
print(np.vsplit(array_19,2))

(2, 4)
Horizontal Split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]])]
Vertical Split
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]])]


<h3> Operasi Aritmetik antar 2 array <h3> 

In [91]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
print(array_a+array_b)

[4 6 8]


In [92]:
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_c-array_d)

[[-5 -5 -5]
 [-5 -5 -5]]


In [93]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_a.sum())
print(array_c.sum())
print(array_c.sum(axis=0))

6
21
[5 7 9]


In [94]:
array_c = np.array([[1,2,3],[4,5,6]])
print(array_c)
print(array_c.sum(axis=0))
print(array_c.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [95]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[5,2,3],[4,5,6]])
print(array_a.max())
print(array_c.max())
print(array_c)
print(array_c.max(axis=0))
print(array_c.min(axis=0))

3
6
[[5 2 3]
 [4 5 6]]
[5 5 6]
[4 2 3]


<h3> Transposing <h3> 

merubah baris jadi kolom, kolom menjadi baris

In [96]:
array_c = np.array([[5,2,3],[4,5,6]])
print(array_c)
print(array_c.shape)

[[5 2 3]
 [4 5 6]]
(2, 3)


In [97]:
print(array_c.T)
print(array_c.T.shape)

[[5 4]
 [2 5]
 [3 6]]
(3, 2)


In [98]:
array_d = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(array_d)
print(array_d.shape)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]
(3, 5)


In [99]:
array_d = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(array_d.T)
print(array_d.T.shape)

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]
 [ 5  8 11]]
(5, 3)


In [100]:
array_random = np.random.random([3,2])*100
print(array_random)

[[ 3.51494167 61.36351433]
 [83.52612838 25.24609077]
 [97.2000091  71.90726577]]


In [101]:
array_random = np.random.random([3,2,3])*100
print(array_random)
print(array_random.flatten())

[[[57.87455064 69.5747982   6.19442712]
  [69.79264654 68.03164798  6.7799517 ]]

 [[21.36746689 79.44193661 20.13237801]
  [23.07246281 51.96098544 32.20781924]]

 [[13.01576949 80.49384876 25.00313789]
  [ 9.73003587 38.76877335 59.14928639]]]
[57.87455064 69.5747982   6.19442712 69.79264654 68.03164798  6.7799517
 21.36746689 79.44193661 20.13237801 23.07246281 51.96098544 32.20781924
 13.01576949 80.49384876 25.00313789  9.73003587 38.76877335 59.14928639]


<h3> Numpy Math formulas<h3>

In [102]:
array_random = np.random.random([3,2])*100
print(array_random)
np.sum(array_random)

[[ 8.56642929 83.14209829]
 [82.22138013 56.05251983]
 [57.35739729 12.81740059]]


300.15722542109313

In [103]:
np.square(9)

81

In [104]:
np.sqrt(9)

3.0

In [105]:
a = np.log(1000000)
print(a)

13.815510557964274


In [106]:
np.exp(a)

999999.9999999995

<h3> Prime Number Generator Based on Interval <h3>

quiz 3

In [107]:
start = int(input("Please, Enter the lowest range value: "))
end = int(input("Please, Enter the upper range value: "))

def is_prime(n):
    if n <= 1:
        return False
    elif n <= 3:
        return True
    elif n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i+2) == 0:
            return False
        i += 6
    return True

print("The Prime Numbers in the range are: ")
for num in range(start, end+1):
    if is_prime(num):
        print(num)

Please, Enter the lowest range value: 1
Please, Enter the upper range value: 20
The Prime Numbers in the range are: 
2
3
5
7
11
13
17
19


In [108]:
print('saadfs \n fdf')

saadfs 
 fdf


In [109]:
for i in range(5):
    print(i)

0
1
2
3
4


In [110]:
import numpy as np
a = np.array([3,2,1])

In [111]:
a[0]

3

In [112]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [113]:
np.arange(0,7,2)

array([0, 2, 4, 6])

In [114]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [115]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [116]:
a.shape

(4,)

In [117]:
b = np.expand_dims(a,axis=0)
b

array([[1, 2, 3, 4]])

In [118]:
c = np.array([[1,2,3],[3,4,5],[6,7,8]])
c
d = c.copy()

In [119]:
c[c>2]

array([3, 3, 4, 5, 6, 7, 8])

In [120]:
np.vstack([c,d])

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [121]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [122]:
c.sum(axis=1)

array([ 6, 12, 21])

In [123]:
we = c*+2

In [124]:
we

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [12, 14, 16]])

In [125]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
x = c.copy()

In [127]:
y = c+2

In [128]:
np.dot(x,c)

array([[ 25,  31,  37],
       [ 45,  57,  69],
       [ 75,  96, 117]])

In [129]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [130]:
np.append(c,[1,2,3,0])

array([1, 2, 3, 3, 4, 5, 6, 7, 8, 1, 2, 3, 0])

In [131]:
q = np.array([1,2,3,0])
np.delete(q,1)

array([1, 3, 0])

In [132]:
np.sort(q)

array([0, 1, 2, 3])

In [133]:
q.sort()
q

array([0, 1, 2, 3])

In [134]:
c.shape

(3, 3)

In [135]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Bilangan prima adalah bilangan yang hanya bisa dibagi 1 dan dirinya sendiri

In [136]:
lower_limit = int(input('Lower Limit :'))
upper_limit = int(input("Upper Limit :"))
print(lower_limit, 'sampai',upper_limit)
for num in range(lower_limit,upper_limit+1):
    if num > 1:
        for i in range(2,num):#Filtering buat bilangan prima
            if (num%i)==0:
                break 
        else:
            print(num) #untuk kita dapat bilangan prima kondisi (num%i)==0 harus dilanggar

Lower Limit :10
Upper Limit :20
10 sampai 20
11
13
17
19


In [137]:
7%2

1

In [138]:
7%3

1